<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KabupatenKota_cityAndProvince</name>
   <tag></tag>
   <elementGuidId>024ab355-09c1-4884-8d4e-81e0de9cb87f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cityAndProvince']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cityAndProvince</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1b1a9d7-882a-4387-8e71-369c7a23f032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c3fce8da-4f5e-4e8c-8267-fb494d6e1782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autocomplete__field_vc5UL</value>
      <webElementGuid>209249c4-7972-4f8c-9130-ad4bda15192a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cityAndProvince</value>
      <webElementGuid>ca9ec434-c9ba-4211-831d-e9581a059d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cityAndProvince</value>
      <webElementGuid>fde8ea22-fee0-4c76-8c97-548c3d93c7d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Kabupaten/Kota</value>
      <webElementGuid>a13afae2-7133-41f5-aedd-ef49cbb5fbc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f58f104c-7a88-48b7-b145-b93b48f0f087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>K</value>
      <webElementGuid>b9e58c24-30c2-4330-9424-7f1687dc652e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cityAndProvince&quot;)</value>
      <webElementGuid>2debdbe5-abf3-49c0-8538-3944b74158e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cityAndProvince']</value>
      <webElementGuid>863cc15a-5e5f-40c2-b01a-5ca8a210bcff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='safe-area']/div/div[2]/div/div[6]/div/input</value>
      <webElementGuid>c8544c56-965c-48b2-8649-e4dcbf80e4b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>11ec1227-7f45-4836-80de-7278caa7c560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cityAndProvince' and @name = 'cityAndProvince' and @placeholder = 'Pilih Kabupaten/Kota' and @type = 'text']</value>
      <webElementGuid>28fde6fd-cc69-4d73-9bb4-603edb5be0a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
