<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Sudah punya akun Masuk</name>
   <tag></tag>
   <elementGuidId>d46d317a-a53d-4a81-824d-ded0ae4e6178</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='safe-area']/div/div[2]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.RegistrationForm_form-container__footer__k6wKc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c5c4d7dd-c015-4c48-a0af-81abc7280815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RegistrationForm_form-container__footer__k6wKc</value>
      <webElementGuid>73c05ce9-2f3f-4996-8d56-18e96b610662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sudah punya akun? Masuk</value>
      <webElementGuid>c028fbed-2df3-4a42-9df0-4433c6791099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;safe-area&quot;)/div[1]/div[@class=&quot;superapp-container content&quot;]/div[@class=&quot;container_Eq-qi&quot;]/p[@class=&quot;RegistrationForm_form-container__footer__k6wKc&quot;]</value>
      <webElementGuid>7adb34af-b29d-40b9-bd66-b61370f8e9a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='safe-area']/div/div[2]/div/p</value>
      <webElementGuid>3fe9c29c-7f65-4461-b0ef-f9cec52c419e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[1]/following::p[2]</value>
      <webElementGuid>9610ab43-9ff0-42e9-9d07-93d532a7814a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarat dan Ketentuan'])[1]/following::p[2]</value>
      <webElementGuid>862d56bf-f05f-4a4d-8d5b-083666a49051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sudah punya akun?']/parent::*</value>
      <webElementGuid>81c0fc03-57cf-463e-81e6-62e0f930e724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p</value>
      <webElementGuid>2a8b0406-35d4-4a6c-8d64-16e4243c83f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Sudah punya akun? Masuk' or . = 'Sudah punya akun? Masuk')]</value>
      <webElementGuid>35921bed-b8d9-4bff-a2a0-a5c77cb88e38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
